/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clients.rszeos;

import java.awt.ComponentOrientation;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.io.PrintWriter;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Anja
 */
public class ClientDesign extends javax.swing.JFrame {
    
    private String pass;
    private boolean isChecked = true;
    private Socket socket; 
    private BufferedReader br;
    private PrintWriter pw;
    private ReceiveMessageFromServer rmfs;

    /**
     * Creates new form ClientDesign
     */
    public ClientDesign() {
        initComponents();
    }
    
    public BufferedReader getBr() {
        return br;
    }
    
    public void setTaCheck(String rec) {
        this.taPoints.setText(rec);
    }
    
    public JComboBox<String> getCbRole() {
        return cbRole;
    }
    
    public JButton getBtnLogin() {
        return btnLogin;
    }

    public JCheckBox getCbHide() {
        return cbHide;
    }

    public JTextField getTfPassword() {
        return tfPassword;
    }

    public JTextField getTfUsername() {
        return tfUsername;
    }
    
    public JLabel getjLabel1() {
        return jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }
    
    public JComboBox<String> getCbAdminTasks() {
        return cbAdminTasks;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public JTextField getTfData() {
        return tfData;
    }
    
    public JButton getBtnOK() {
        return btnOK;
    }
    
    public JLabel getjLabel6() {
        return jLabel6;
    }
    
    public JComboBox<String> getCbStudents() {
        return cbStudents;
    }

    public JComboBox<String> getCbSubjects() {
        return cbSubjects;
    }
    
    public JComboBox<String> getCbChooseCategory() {
        return cbChooseCategory;
    }

    public JComboBox<String> getCbChooseSubject() {
        return cbChooseSubject;
    }
    
    public JButton getBtnChooseSubject() {
        return btnChooseSubject;
    }

    public JTextField getTfPoints() {
        return tfPoints;
    }
    

    public JLabel getjLabel10() {
        return jLabel10;
    }
    
    public JButton getBtnSeeGrades() {
        return btnSeeGrades;
    }

    public JButton getBtnSeePoints() {
        return btnSeePoints;
    }
    
    public JTextArea getTaGrades() {
        return taGrades;
    }

    public JTextArea getTaPoints() {
        return taPoints;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfUsername = new javax.swing.JTextField();
        tfPassword = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        cbRole = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        taPoints = new javax.swing.JTextArea();
        cbHide = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        cbAdminTasks = new javax.swing.JComboBox<>();
        tfData = new javax.swing.JTextField();
        btnOK = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnAssign = new javax.swing.JButton();
        cbStudents = new javax.swing.JComboBox<>();
        cbSubjects = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        btnUpdatePoints = new javax.swing.JButton();
        cbChooseSubject = new javax.swing.JComboBox<>();
        cbChooseCategory = new javax.swing.JComboBox<>();
        btnChooseSubject = new javax.swing.JButton();
        tfPoints = new javax.swing.JTextField();
        btnAddPoints = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnSeePoints = new javax.swing.JButton();
        btnSeeGrades = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        taGrades = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("username:");

        jLabel2.setText("password:");

        jLabel3.setText("role:");

        btnLogin.setText("login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        cbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "admin", "student" }));
        cbRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRoleActionPerformed(evt);
            }
        });

        taPoints.setEnabled(false);
        taPoints.setColumns(20);
        taPoints.setRows(5);
        jScrollPane1.setViewportView(taPoints);

        cbHide.setText("hide");
        cbHide.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbHideItemStateChanged(evt);
            }
        });

        jLabel5.setEnabled(false);
        jLabel5.setText("Choose the activity:");

        cbAdminTasks.setEnabled(false);
        cbAdminTasks.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Empty", "Adding new students", "Adding new subjects", "Assigning subjects to students", "Adding new admins" }));
        cbAdminTasks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAdminTasksActionPerformed(evt);
            }
        });

        tfData.setEnabled(false);

        btnOK.setEnabled(false);
        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        jLabel6.setEnabled(false);
        jLabel6.setText("Format-");

        jLabel7.setEnabled(false);
        jLabel7.setText("Students");

        jLabel8.setEnabled(false);
        jLabel8.setText("Subjects");

        btnAssign.setEnabled(false);
        btnAssign.setText("assign");
        btnAssign.setActionCommand("Assign");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });

        cbStudents.setEnabled(false);

        cbSubjects.setEnabled(false);

        jLabel9.setEnabled(false);
        jLabel9.setText("Update points to selected student?");

        btnUpdatePoints.setEnabled(false);
        btnUpdatePoints.setText("YES");
        btnUpdatePoints.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatePointsActionPerformed(evt);
            }
        });

        cbChooseSubject.setEnabled(false);

        cbChooseCategory.setEnabled(false);

        btnChooseSubject.setEnabled(false);
        btnChooseSubject.setText("choose");
        btnChooseSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseSubjectActionPerformed(evt);
            }
        });

        tfPoints.setEnabled(false);

        btnAddPoints.setEnabled(false);
        btnAddPoints.setText("add");
        btnAddPoints.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPointsActionPerformed(evt);
            }
        });

        jLabel10.setEnabled(false);
        jLabel10.setText("Choose the activity:");

        btnSeePoints.setEnabled(false);
        btnSeePoints.setText("See points");
        btnSeePoints.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeePointsActionPerformed(evt);
            }
        });

        btnSeeGrades.setEnabled(false);
        btnSeeGrades.setText("See grades");
        btnSeeGrades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeeGradesActionPerformed(evt);
            }
        });

        taGrades.setEnabled(false);
        taGrades.setColumns(20);
        taGrades.setRows(5);
        jScrollPane2.setViewportView(taGrades);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSeePoints, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(btnLogin))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(42, 42, 42)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tfPassword)
                                            .addComponent(cbRole, 0, 93, Short.MAX_VALUE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbHide)))
                        .addGap(30, 30, 30)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbAdminTasks, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(61, 61, 61)
                                        .addComponent(btnUpdatePoints)))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfPoints)
                                    .addComponent(cbChooseCategory, 0, 87, Short.MAX_VALUE)
                                    .addComponent(cbChooseSubject, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnChooseSubject, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAddPoints, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(cbStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(57, 57, 57)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(cbSubjects, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnAssign))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(tfData, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnOK)))
                                .addGap(0, 13, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addComponent(btnSeeGrades, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(210, 210, 210))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(cbAdminTasks, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(cbHide))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnLogin))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnOK))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbStudents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbSubjects, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAssign))))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbChooseSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnChooseSubject))
                        .addGap(8, 8, 8)
                        .addComponent(cbChooseCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddPoints)
                            .addComponent(tfPoints, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdatePoints)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSeePoints)
                            .addComponent(btnSeeGrades))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        try {
            //creating new socket
            this.socket = new Socket("127.0.0.1", 6002);
            //br i pw for reading and sending messages to server
            this.br = new BufferedReader(new InputStreamReader(this.socket.getInputStream()));
            this.pw = new PrintWriter(new OutputStreamWriter(this.socket.getOutputStream()), true);
            //creating thread for each client
            //this refers to ClientDesign for further updates
            this.rmfs = new ReceiveMessageFromServer(this);
            Thread thr = new Thread(rmfs);
            thr.start();
            
            String porukaZaSlanje;
            if(!this.tfUsername.getText().equals("") && !this.tfPassword.getText().equals("")){
                if('*' == this.tfPassword.getText().charAt(0)){
                //username:password:role
                    porukaZaSlanje = this.tfUsername.getText() + ":" + this.pass + ":" + this.cbRole.getSelectedItem(); 
                }else{
                    porukaZaSlanje = this.tfUsername.getText() + ":" + this.tfPassword.getText() + ":" + this.cbRole.getSelectedItem(); 
                }
                this.pw.println(porukaZaSlanje);
            } else {
                JOptionPane.showMessageDialog(null, "Wrong input");
            }

        } catch (IOException ex) {
            Logger.getLogger(ClientDesign.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void cbRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbRoleActionPerformed

    private void cbHideItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbHideItemStateChanged
        if(isChecked){
            this.pass = this.tfPassword.getText();
            String hiddenPass = "";
            for( int i = 0; i < this.tfPassword.getText().length(); i++){
                hiddenPass = hiddenPass + "*";
            }
            this.tfPassword.setText(hiddenPass);
            this.isChecked = false;
        }else{
            this.tfPassword.setText(this.pass);
            this.isChecked = true;
        }
        
        
    }//GEN-LAST:event_cbHideItemStateChanged

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        this.pw.println(this.tfData.getText());
    }//GEN-LAST:event_btnOKActionPerformed

    private void cbAdminTasksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAdminTasksActionPerformed
        switch (this.cbAdminTasks.getSelectedIndex()) {
            case 1:
                this.jLabel6.setEnabled(true);
                this.jLabel6.setText("Format-Student:name,surname,index,JMBG,username,pass");
                this.btnOK.setEnabled(true);
                this.tfData.setEnabled(true);
                this.jLabel7.setEnabled(false);
                this.jLabel8.setEnabled(false);
                this.btnAssign.setEnabled(false);
                this.cbStudents.setEnabled(false);
                this.cbSubjects.setEnabled(false);
                this.cbChooseSubject.setEnabled(false);
                this.btnChooseSubject.setEnabled(false);
                this.cbChooseCategory.setEnabled(false);
                this.jLabel9.setEnabled(false);
                this.btnUpdatePoints.setEnabled(false);
                this.btnAddPoints.setEnabled(false);
                this.tfPoints.setEnabled(false);
                break;
            case 2:
                this.jLabel6.setEnabled(true);
                this.jLabel6.setText("Format-Subject:ime;T1 min1 max1,T2 min2 max2");
                this.btnOK.setEnabled(true);
                this.tfData.setEnabled(true);
                this.jLabel7.setEnabled(false);
                this.jLabel8.setEnabled(false);
                this.btnAssign.setEnabled(false);
                this.cbStudents.setEnabled(false);
                this.cbSubjects.setEnabled(false);
                this.cbChooseSubject.setEnabled(false);
                this.btnChooseSubject.setEnabled(false);
                this.cbChooseCategory.setEnabled(false);
                this.jLabel9.setEnabled(false);
                this.btnUpdatePoints.setEnabled(false);
                this.btnAddPoints.setEnabled(false);
                this.tfPoints.setEnabled(false);
                break;
            case 3:
                this.jLabel6.setEnabled(false);
                this.btnOK.setEnabled(false);
                this.tfData.setEnabled(false);
                this.jLabel7.setEnabled(true);
                this.jLabel8.setEnabled(true);
                this.btnAssign.setEnabled(true);
                this.cbStudents.setEnabled(true);
                this.cbSubjects.setEnabled(true);
                this.jLabel9.setEnabled(true);
                this.btnUpdatePoints.setEnabled(true);
                this.cbChooseCategory.setEnabled(true);
                this.cbChooseSubject.setEnabled(true);
                this.btnChooseSubject.setEnabled(true);
                this.btnAddPoints.setEnabled(true);
                this.tfPoints.setEnabled(true);
                this.pw.println("Students and Subjects:give me lists");
                break;
            case 4:
                this.jLabel6.setEnabled(true);
                this.jLabel6.setText("Format-Admin:username;password");
                this.btnOK.setEnabled(true);
                this.tfData.setEnabled(true);
                this.jLabel7.setEnabled(false);
                this.jLabel8.setEnabled(false);
                this.btnAssign.setEnabled(false);
                this.cbStudents.setEnabled(false);
                this.cbSubjects.setEnabled(false);
                this.cbChooseSubject.setEnabled(false);
                this.btnChooseSubject.setEnabled(false);
                this.cbChooseCategory.setEnabled(false);
                this.jLabel9.setEnabled(false);
                this.btnUpdatePoints.setEnabled(false);
                this.btnAddPoints.setEnabled(false);
                this.tfPoints.setEnabled(false);
                
            default:
                break;
        }
    }//GEN-LAST:event_cbAdminTasksActionPerformed

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
                pw.println("Assigning:" + this.getCbStudents().getSelectedItem() + 
                ":" + this.getCbSubjects().getSelectedItem());
                this.cbChooseSubject.removeAllItems();
                this.cbChooseCategory.removeAllItems();
    }//GEN-LAST:event_btnAssignActionPerformed

    private void btnUpdatePointsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatePointsActionPerformed
        //sending selected student to update his points
        pw.println("Selected student:" + this.cbStudents.getSelectedItem());
    }//GEN-LAST:event_btnUpdatePointsActionPerformed

    private void btnChooseSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseSubjectActionPerformed
        pw.println("Selected subject:" + this.cbStudents.getSelectedItem() + ";" + this.cbChooseSubject.getSelectedItem());
    }//GEN-LAST:event_btnChooseSubjectActionPerformed

    private void btnAddPointsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPointsActionPerformed
        pw.println("Adding points:" + this.cbStudents.getSelectedItem() + ";" + this.cbChooseSubject.getSelectedItem() + ";" + 
                this.cbChooseCategory.getSelectedItem() + ";" + this.tfPoints.getText());
    }//GEN-LAST:event_btnAddPointsActionPerformed

    private void btnSeePointsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeePointsActionPerformed
        pw.println("See points:" + this.tfUsername.getText());
    }//GEN-LAST:event_btnSeePointsActionPerformed

    private void btnSeeGradesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeeGradesActionPerformed
        pw.println("See grades:" + this.tfUsername.getText());
    }//GEN-LAST:event_btnSeeGradesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientDesign().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPoints;
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnChooseSubject;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnSeeGrades;
    private javax.swing.JButton btnSeePoints;
    private javax.swing.JButton btnUpdatePoints;
    private javax.swing.JComboBox<String> cbAdminTasks;
    private javax.swing.JComboBox<String> cbChooseCategory;
    private javax.swing.JComboBox<String> cbChooseSubject;
    private javax.swing.JCheckBox cbHide;
    private javax.swing.JComboBox<String> cbRole;
    private javax.swing.JComboBox<String> cbStudents;
    private javax.swing.JComboBox<String> cbSubjects;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea taGrades;
    private javax.swing.JTextArea taPoints;
    private javax.swing.JTextField tfData;
    private javax.swing.JTextField tfPassword;
    private javax.swing.JTextField tfPoints;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables

}
